[project]
name = "netbox-storage-plugin"
version = "0.1.0"
description = "A NetBox plugin for managing storage volumes"

[tool.setuptools]
packages = ["netbox_storage_plugin"]

[tool.setuptools.package-data]
"*" = ["templates/*", "static/*"]