# Generated by Django 5.1.4 on 2025-03-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('netbox_storage_plugin', '0003_alter_disk_options_alter_diskset_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disk',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='object_id',
        ),
        migrations.AddField(
            model_name='disk',
            name='associated_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='associated_object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]