# Generated by Django 5.1.4 on 2025-03-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_storage_plugin', '0004_remove_disk_content_type_remove_disk_object_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disk',
            options={'ordering': ['name'], 'permissions': [('netbox_storage_plugin.view_disk', 'Can view disks'), ('netbox_storage_plugin.manage_disk', 'Can manage disks')]},
        ),
        migrations.RenameField(
            model_name='diskset',
            old_name='object_id',
            new_name='associated_object_id',
        ),
        migrations.RenameField(
            model_name='diskset',
            old_name='content_type',
            new_name='associated_object_type',
        ),
        migrations.RenameField(
            model_name='diskset',
            old_name='parent_content_type',
            new_name='parent_object_type',
        ),
        migrations.RenameField(
            model_name='filesystem',
            old_name='object_id',
            new_name='associated_object_id',
        ),
        migrations.RenameField(
            model_name='filesystem',
            old_name='content_type',
            new_name='associated_object_type',
        ),
        migrations.RenameField(
            model_name='filesystem',
            old_name='parent_content_type',
            new_name='parent_object_type',
        ),
        migrations.RenameField(
            model_name='logicaldrive',
            old_name='object_id',
            new_name='associated_object_id',
        ),
        migrations.RenameField(
            model_name='logicaldrive',
            old_name='content_type',
            new_name='associated_object_type',
        ),
        migrations.RenameField(
            model_name='logicaldrive',
            old_name='parent_content_type',
            new_name='parent_object_type',
        ),
        migrations.RenameField(
            model_name='objectstorage',
            old_name='object_id',
            new_name='associated_object_id',
        ),
        migrations.RenameField(
            model_name='objectstorage',
            old_name='content_type',
            new_name='associated_object_type',
        ),
        migrations.RenameField(
            model_name='objectstorage',
            old_name='parent_content_type',
            new_name='parent_object_type',
        ),
        migrations.RenameField(
            model_name='sanvolume',
            old_name='object_id',
            new_name='associated_object_id',
        ),
        migrations.RenameField(
            model_name='sanvolume',
            old_name='content_type',
            new_name='associated_object_type',
        ),
        migrations.RenameField(
            model_name='sanvolume',
            old_name='parent_content_type',
            new_name='parent_object_type',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='object_id',
            new_name='associated_object_id',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='content_type',
            new_name='associated_object_type',
        ),
        migrations.RenameField(
            model_name='share',
            old_name='parent_content_type',
            new_name='parent_object_type',
        ),
        migrations.RenameField(
            model_name='vmdisk',
            old_name='object_id',
            new_name='associated_object_id',
        ),
        migrations.RenameField(
            model_name='vmdisk',
            old_name='content_type',
            new_name='associated_object_type',
        ),
        migrations.RenameField(
            model_name='vmdisk',
            old_name='parent_content_type',
            new_name='parent_object_type',
        ),
        migrations.AddField(
            model_name='disk',
            name='state',
            field=models.CharField(default='active', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diskset',
            name='state',
            field=models.CharField(default='acgttive', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filesystem',
            name='state',
            field=models.CharField(default='active', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logicaldrive',
            name='state',
            field=models.CharField(default='active', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectstorage',
            name='state',
            field=models.CharField(default='active', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanvolume',
            name='state',
            field=models.CharField(default='active', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='share',
            name='state',
            field=models.CharField(default='active', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vmdisk',
            name='state',
            field=models.CharField(default='active', max_length=50),
            preserve_default=False,
        ),
    ]